### ISSUE TITLE
Allow crypted files to be stored in a subdirectory

### ISSUE THREAD

**Issue by Cyberuben** [hjanuschka/fastlane-plugin-cryptex#13]
Hi,

Yesterday I tried to import a file named `test.txt` and store it with a key such as `android/serviceaccounts/test.txt`, however, I got greeted with some issues related to `ENOENT`, probably because the folder `android/serviceaccounts` doesn't exist. Is it possible to set up some sort of `mkdir -p` before trying to write the crypted file?

Unfortunately I do not have any Ruby experience otherwise I would have done it myself.

**Comment by Cyberuben** [comment]
I created PR #14, I'd love to see it being merged

**Comment by hjanuschka** [comment]
merged, many thx
